Q: why this does not compile?
```
error[E0597]: `block` does not live long enough
   --> src/compiler.rs:388:31
    |
62  | impl<'run: 'c, 'c> Compiler<'run, 'c> {
    |                -- lifetime `'c` defined here
...
386 |         let block: ir::Block<'c> = ir::Block::new(&[]);
    |             ----- binding `block` declared here
387 |         for expr in exprs {
388 |             self.compile_expr(&block, ctx, expr)?;
    |             ------------------^^^^^^------------
    |             |                 |
    |             |                 borrowed value does not live long enough
    |             argument requires that `block` is borrowed for `'c`
...
397 |     }
    |     - `block` dropped here while still borrowed

error[E0505]: cannot move out of `block` because it is borrowed
   --> src/compiler.rs:395:29
    |
62  | impl<'run: 'c, 'c> Compiler<'run, 'c> {
    |                -- lifetime `'c` defined here
...
386 |         let block: ir::Block<'c> = ir::Block::new(&[]);
    |             ----- binding `block` declared here
387 |         for expr in exprs {
388 |             self.compile_expr(&block, ctx, expr)?;
    |             ------------------------------------
    |             |                 |
    |             |                 borrow of `block` occurs here
    |             argument requires that `block` is borrowed for `'c`
...
395 |         region.append_block(block);
    |                             ^^^^^ move out of `block` occurs here

Some errors have detailed explanations: E0505, E0597.
For more information about an error, try `rustc --explain E0505`.
```